FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN chmod +x /app/service_discovery.py

EXPOSE 5000

CMD ["python", "service_discovery.py"]